name: arcgis_maps_flutter
description: A new flutter plugin project.
version: 1.0.0+56
homepage: https://github.com/valentingrigorean/arcgis_maps_flutter

environment:
  sdk: "^3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.16
  plugin_platform_interface: ^2.1.6
  stream_transform: ^2.1.0
  collection:
  fluster: ^1.2.0
  equatable: ^2.0.5
  http: ^1.1.0
  xml2json: ^6.2.0
  jiffy: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  plugin:
    platforms:
      android:
        package: com.valentingrigorean.arcgis_maps_flutter
        pluginClass: ArcgisMapsFlutterPlugin
      ios:
        pluginClass: ArcgisMapsFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
     - assets/ic_compass.png
     - assets/2.0x/ic_compass.png
     - assets/3.0x/ic_compass.png
