name: arcgis_maps_flutter
description: A new flutter plugin project.
version: 0.0.6+43
homepage: https://github.com/valentingrigorean/arcgis_maps_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.13
  plugin_platform_interface: ^2.1.4
  stream_transform: ^2.1.0
  collection: ^1.17.1
  fluster: ^1.2.0
  equatable: ^2.0.5
  http: ^0.13.5
  xml2json: ^5.3.6
  jiffy: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  build_runner: ^2.3.3

flutter:
  plugin:
    platforms:
      android:
        package: com.valentingrigorean.arcgis_maps_flutter
        pluginClass: ArcgisMapsFlutterPlugin.kt
      ios:
        pluginClass: ArcgisMapsFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
     - assets/ic_compass.png
     - assets/2.0x/ic_compass.png
     - assets/3.0x/ic_compass.png
